### ISSUE TITLE
Support Java 10

### ISSUE THREAD

**Issue by udalrich** [j-tim/docker-docker-compose-jdk-mvn#1]
A version that supports Java 10 would be helpful.

**Comment by j-tim** [comment]
Hi @udalrich we will add support for Java 10 in the near future.

**Comment by j-tim** [comment]
Just pushed an initial Java 11 version to Dockerhub does that work for you?
For more details see #2

**Comment by j-tim** [comment]
We will focus on Java 11 support so i'll close this issue.
