### ISSUE TITLE
Support Java 11

### ISSUE THREAD

**Issue by s7ygian** [j-tim/docker-docker-compose-jdk-mvn#2]
A version that supports Java 11 would be helpful.

**Comment by j-tim** [comment]
Thanks for submitting an issue. At the moment OpenJdk 11 is not supported by Alpine see: https://github.com/docker-library/openjdk/issues/211 since this docker image rely on the official Docker images (based on Alpine as well) we need to find an alternative for having docker, docker compose, openjdk 11 and maven in one image without depending on Alpine.

**Comment by s7ygian** [comment]
What about using the AdoptOpenJDK (https://hub.docker.com/r/adoptopenjdk/openjdk11) or Zulu alpine builds (https://www.azul.com/downloads/zulu/zulu-download-alpine/) instead?

**Comment by j-tim** [comment]
Thanks for your response and suggestions. I'll take a look at both options and see what fits best in the current setup.

**Comment by j-tim** [comment]
Just pushed an initial test version based on Adopt Open JDK 11 to Dockerhub:

```
docker pull jtim/docker-docker-compose-jdk-mvn:18.09.3-ce-git-compose-1.23.2-adoptopenjdk-11.0.2.9-maven-3.6.0
```

Sorry for the long tag name i will make shorter tags when this version is completely working. 
Can you give it a try in your pipeline? Just checked this version with a simple Spring Boot app (Java 11).

**Comment by s7ygian** [comment]
Thanks, it works so far. :) Is it possible to set the AdoptOpenJDK edition (either OpenJ9 or Hotspot) for this docker image?

**Comment by j-tim** [comment]
Ok great. I'll close this ticket and create new ticket one for Java 9 based on AdoptOpenJDK.

**Comment by s7ygian** [comment]
Sorry, I meant the AdoptOpenJDK-11 variants OpenJ9 and Hotspot, not Java 9, see: https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9 :)

**Comment by j-tim** [comment]
Ok no problem. I'll take a look at #4 to support AdoptOpenJDK-11 variants OpenJ9 and Hotspot
