### ISSUE TITLE
Support AdoptOpenJDK-11 variants

### ISSUE THREAD

**Issue by s7ygian** [j-tim/docker-docker-compose-jdk-mvn#4]
Please support the AdoptOpenJDK-11 variants OpenJ9 and Hotspot, see: https://adoptopenjdk.net/releases.html?variant=openjdk11&jvmVariant=openj9

**Comment by j-tim** [comment]
I'll take a look

**Comment by s7ygian** [comment]
Any news on this yet?

**Comment by j-tim** [comment]
Which one do you like to be supported first OpenJ9 or Hotspot?

**Comment by j-tim** [comment]
Initial versions available:
* OpenJ9: jtim/docker-docker-compose-jdk-mvn:18.09.6-ce-git-compose-1.24.0-adoptopenjdk-11.0.3_7_openj9-0.14.3-maven-3.6.1
* Hotspot: jtim/docker-docker-compose-jdk-mvn:18.09.6-ce-git-compose-1.24.0-adoptopenjdk-11.0.3_7-maven-3.6.1

Will do some more test in the upcoming days and update the documentation.
@s7ygian let me know if this works for you.
