### ISSUE TITLE
can't chmod +x sh files

### ISSUE THREAD

**Issue by webmutation** [j-tim/docker-docker-compose-jdk-mvn#5]
Hi,
I need to be able to chmod +x some files so they are runnable to test connection on a kafka cluster, however when i try to do this using this image i get a Operation not permitted.

**Comment by j-tim** [comment]
Hi @webmutation are you running this image in a Gitlab CI pipeline?
Are those files you have to chmod under version control and available during the build?

**Comment by webmutation** [comment]
Hi, yes inside GItlab CI pipeline.
No the file is XL Release/Deploy CLI tool that is downloaded
- curl -LO https://dist.xebialabs.com/public/xl-cli/8.6.1/linux-amd64/xl
- chmod +x xl

**Comment by j-tim** [comment]
Hi, what version of the image are you using?  
I just tested to curl and chmod the file in a Gitlab pipeline and seems to work file

Example job from my gitlab-ci.yml:

```
adoptopenjdk-11.0.3_7-hotspot:
  image: jtim/docker-docker-compose-jdk:18.09.6-ce-git-compose-1.24.0-adoptopenjdk-11.0.3_7
  stage:java-11
  services:
    - docker:dind
  script:
    - curl -LO https://dist.xebialabs.com/public/xl-cli/8.6.1/linux-amd64/xl
    - chmod +x xl
```

Output from the pipeline:

```
$ curl -LO https://dist.xebialabs.com/public/xl-cli/8.6.1/linux-amd64/xl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 33 14.7M   33 5104k    0     0  2748k      0  0:00:05  0:00:01  0:00:04 2747k
100 14.7M  100 14.7M    0     0  6183k      0  0:00:02  0:00:02 --:--:-- 6183k
$ chmod +x xl
```

**Comment by webmutation** [comment]
Hi, I am using 
image: jtim/docker-docker-compose-jdk-mvn:latest

And now i have another issue... I have a build job and then a test job, and since you have bob-the-builder as home directory it does not allow to write to that location...

**Comment by j-tim** [comment]
Hi @webmutation do you have sample gitlab-ci.yml pipeline for me to reproduce the issue?

**Comment by j-tim** [comment]
No feedback provided. Closing this issue. Feel free to open a new one in case you are still facing this issue.
