### ISSUE TITLE
Update image for Java 11

### ISSUE THREAD

**Issue by j-tim** [j-tim/docker-docker-compose-jdk-mvn#8]

**Comment by minal1390** [comment]
@j-tim Any plan to create image with Docker + docker compose + maven + Java 11 + jq?

**Comment by j-tim** [comment]
Hi @minal1390 yes I'm working on the Java 11 images.
They will be there soon.

**Comment by j-tim** [comment]
@minal1390 the Java 11 images are available. 
Give it a try.

**Comment by minal1390** [comment]
@j-tim I've tested the new image with java11 and it works. 
Thank you.

**Comment by j-tim** [comment]
Thanks for your feedback @minal1390
